### ISSUE TITLE
difference between checked_add vs saturating_add

### ISSUE THREAD

**Issue by frankli-dev** [encointer/substrate-fixed#11]
I know that there is a description on the docs about `checked_add` & `saturating_add`. But I'm not sure about that exactly and also got different result with the following.

a : 100_000_000_000_000_000_000,
b : 100_000_000_000_000_000_000

both are `FixedU128<U64>`
```
let c = a.saturating_add(b)
```

`checked_add` causes the error but `saturating_add` calculates it correctly.

I'm not sure why `checked_add` fails. Please explain. Thanks

**Comment by brenzi** [comment]
"checked" means that you get an error if it fails so that you can treat it gracefully. "saturating" avoids an error by just letting the result be the max_value. But that's all standard rust, nothing specific to our crate
