### ISSUE TITLE
Readme is inconsistent

### ISSUE THREAD

**Issue by apopiak** [encointer/substrate-fixed#2]
The second sentence in the Readme is
> Additionally, transcendental functions have been added (log, exp, pow, trigonometry).

But later on it says

> This crate does not provide general analytic functions.
> * No algebraic functions are provided, for example no `sqrt` or `pow`.
> * No trigonometric functions are provided, for example no `sin` or `cos`.
> * No other transcendental functions are provided, for example no `log` or `exp`.

Can you update it to the current state?

**Comment by brenzi** [comment]
thanks, that's true. Everything after the first sentence is forked from the upstream crate. Will update this

**Comment by JoshOrndorff** [comment]
Also, there are no docs about how to use the transcendental functions.

**Comment by JoshOrndorff** [comment]
Also the docs say I can use

```toml
[dependencies]
fixed = "0.5.4"
```

but that will get me the crate you forked, not this crate.

**Comment by brenzi** [comment]
true, thanks. sorry for the confusion leading you to crates.io.
fixd.
