### ISSUE TITLE
sqrt of certain numbers returns unexpectedly an error

### ISSUE THREAD

**Issue by clangenb** [encointer/substrate-fixed#6]
e.g. `sqrt(0.0000000002)` returns an error.

**Comment by brenzi** [comment]
As sqrt of numbers in the range 0..1 are calculated based on their inverse we may have to define a lower bound for the fixpoint approximation to be valid

https://github.com/encointer/substrate-fixed/blob/2c52170fa02507dc5b52c516061302670860869a/src/transcendental.rs#L143

change that line not to check for equality to zero but *smaller than* a minimal supported value. a WARNING should be issued in that case

**Comment by brenzi** [comment]
but should we really avoid that error? shouldn't it be an error?

**Comment by clangenb** [comment]
Hmm, I think we can not so easily circumvent this on substrate fixed side. But a warning would be nice at least.

We could address that bug in the pallet and increase the minimum supported distance between meetup points of a currency. The problematic case was 290 meters apart.

**Comment by clangenb** [comment]
Problematic numbers are within : ]1.164e-10, 5.82e-10] with the types I32F32.

**Comment by clangenb** [comment]
Here we get an overflow: https://github.com/encointer/substrate-fixed/blob/2c52170fa02507dc5b52c516061302670860869a/src/transcendental.rs#L148

**Comment by clangenb** [comment]
Edit: numbers below 1.64 simply get truncated to 0, this is why it works. Hence, there is only a lower bound of `5.82e-10` that can be calculated.

**Comment by clangenb** [comment]
I just changed the error type in the sqrt function to `&'static str`, which prints the overflow error. I think this suffices as error handling.
